2012-11-05
Changed text color options to bold.

Changed order of functions to more closely match build_pkg order.

Added --chrootpacman operation.

diff --git a/aurch b/aurch
--- a/aurch
+++ b/aurch
@@ -1,32 +1,32 @@
 #!/bin/bash
-# aurch 2021-11-03
-# dependencies: arch-install-scripts base-devel git [AUR: aurutils -or- AUR fallback: auracle]
+# aurch 2021-11-04
+# dependencies: arch-install-scripts base-devel git [AUR: 'aurutils' -or- fallback 'auracle']
 # Aurch sets up a chroot and builds AUR packages from within it.
-# * Can also be used with aurutils, see aur_dep_order function for details.
 
-basedir="$(pwd)"									# ie: /home/user/Testing/3/
-[[ ! -s ${basedir}/.#ID ]] && mktemp -u XXX > .#ID					# Create chroot suffix if not present
-chroot="${basedir}/chroot-$(< .#ID)"							# ie: /home/user/Testing/4/chroot-xxx
-package="${2,,}"									# ${var,,} convert to lower case for ie: 'PKGBUILDer'
-buildpkg="${2,,}"									# ie: /home/user/Testing/5/chroot-xxx/home/builduser
-chrbuilduser="/home/builduser"
-homebuilduser="${basedir}/chroot-$(< .#ID)/home/builduser"
-[[ ! -d /tmp/aurch ]] && mkdir /tmp/aurch
-[[ ! -v AURREPO ]] && AURREPO="/tmp/aurch"
-czm=$(echo -e '\033[1;96m'":: aurch ==>"'\033[00m')
-error=$(echo -e '\033[1;91m' "ERROR:" '\033[00m')
-line2=$(printf %"$(tput cols)"s |tr " " "-")						#  set line '---' to terminal width
+#========================================================================================================================#
 
-# Colors for ':: aurch ==>' above.
+basedir="$(pwd)"								# directory aurch script is ran in ie: /home/aurch-chroot/
+[[ ! -s ${basedir}/.#ID ]] && mktemp -u XXX > .#ID				# creates unique chroot suffix if not present
+chroot="${basedir}/chroot-$(< .#ID)"						# from host: path to ${basedir} ie: /home/aurch-chroot/chroot-xxx
+chrbuilduser="/home/builduser"							# in chroot: path to builduser home directory
+homebuilduser="${basedir}/chroot-$(< .#ID)/home/builduser"			# from host: path to builduser home directory
+package="${2,,}"								# ${var,,} convert to lower case ie: 'PKGBUILDer'
+buildpkg="${2,,}"								# ${var,,} convert to lower case
+[[ ! -v AURREPO ]] && AURREPO="/tmp/aurchx"					# host 'local pacman aur repo' or 'aur package cache'
+[[ ! -d ${AURREPO} ]] && mkdir ${AURREPO}					# create aur repo directory if not present
+czm=$(echo -e '\033[1;96m'":: aurch ==>"'\033[00m')				# cyan  color ':: aurch ==>' text
+error=$(echo -e '\033[1;91m' "ERROR:" '\033[00m')				# red  color 'ERROR' text
+line2=$(printf %"$(tput cols)"s |tr " " "-")					# set line '---' to terminal width
 
+# Colors for text:
 # Black		'\033[1;90m'
-# Red		'\033[0;91m'
-# Green		'\033[0;92m'
-# Yellow	'\033[0;93m'
-# Blue		'\033[0;94m'
-# Purple	'\033[0;95m'
-# Cyan		'\033[0;96m'
-# White		'\033[0;97m'
+# Red		'\033[1;91m'
+# Green		'\033[1;92m'
+# Yellow	'\033[1;93m'
+# Blue		'\033[1;94m'
+# Purple	'\033[1;95m'
+# Cyan		'\033[1;96m'
+# White		'\033[1;97m'
 # cancel	'\033[00m'
 
 #========================================================================================================================#
@@ -52,14 +52,15 @@ DESCRIPTION
 ${line2}
 
 Usage:
-		aurch [operation] [package]
+		aurch [operation] [package] [--chrootpacman <pacman commands> <packages>]
 
 
 Operations: 
-		    --setup	Sets up a chroot
-		-B, --build	Builds an AUR package in chroot
-		    --pgp	Manually import pgp key in chroot
-		-h, --help	Prints help
+		    --setup		Sets up a chroot
+		-B, --build		Builds an AUR package in chroot
+		    --chrootpacman	Manually run pacman in chroot
+		    --pgp		Manually import pgp key in chroot
+		-h, --help		Prints help
 
 
 Examples:
@@ -85,6 +86,7 @@ EOF
 	echo "${czm} Aurch runtime messages will be proceeded with this."
 	echo "${czm}${error}Aurch runtime errors will be proceeded with this."; echo
 }
+
 #========================================================================================================================#
 
 set_up(){
@@ -126,7 +128,7 @@ if	[[ -d  ${chroot}/build ]] && [[ -d ${homebuilduser} ]] ; then
 	echo "${czm} Do not mess with aurch #.ID in the base directory."; echo
 
 	echo "Do not mess with the aurch #.ID file in the base directory." > aurch.README
-	echo "The chroot has user builduser setup with sudo no password." >> aurch.README	# SC2129: Not commands in the message.
+	echo "The chroot has user builduser setup with sudo no password." >> aurch.README	# SC2129: Considered and chose not to.
 	echo "The chroot AUR package cache is in /build. This cache"      >> aurch.README
 	echo "contains both requested and makedepends AUR builds."        >> aurch.README
 	echo "Edit AURREPO path to point to your local pacman aur repo"   >> aurch.README
@@ -151,7 +153,9 @@ fi
 
 }
 
-is_it_available
+if	[[ ! ${1} == --chrootpacman ]] ; then
+	is_it_available
+fi
 
 #========================================================================================================================#
 
@@ -184,6 +188,7 @@ fi
 	cd "${homebuilduser}/${buildpkg}"						|| { echo "[line ${LINENO}]" ; exit ; }
 
 if	[[ -n ${buildpkg} ]] ; then
+	echo; echo "${czm} Building AUR package ${buildpkg} in chroot."; echo
 	sudo systemd-nspawn -q -D "${chroot}" -u builduser --chdir="${chrbuilduser}/${buildpkg}" --pipe \
 	makepkg -scr --noconfirm
 fi
@@ -197,6 +202,31 @@ if	[[ -n ${pkgs} ]] ; then
 	echo "${czm} In AURREPO: ${aurrepo}"; echo
 fi
 	unset buildpkg
+}
+
+#========================================================================================================================#
+
+fetch_source(){
+
+	cd "${homebuilduser}" || { echo "Is chroot not setup? Run: aurch --setup before -B." ; exit ; }
+
+if	[[ -d  "${package}" ]] && [[ -d "${package}"/.git ]]; then
+
+	cd "${package}"										|| { echo "[line ${LINENO}]" ; exit ; }
+	git pull
+	git cat-file -p "$(git rev-parse HEAD)":./PKGBUILD >PKGBUILD
+
+	sudo systemd-nspawn -q -D "${chroot}" -u builduser --chdir="${chrbuilduser}/${package}" --pipe \
+	makepkg --printsrcinfo >.SRCINFO						# SC2024: Is not ran as sudo within chroot.
+	cd "${homebuilduser}"									|| { echo "[line ${LINENO}]" ; exit ; }
+else
+	if	! git clone https://aur.archlinux.org/"${package}".git ; then
+		echo; echo "${czm}  Git clone failed. Switching to snapshot download."; echo
+		curl -L -O https://aur.archlinux.org/cgit/aur.git/snapshot/"${package,,}".tar.gz
+		tar xvzf   "${package}.tar.gz"
+	fi
+fi
+
 }
 
 #========================================================================================================================#
@@ -231,6 +261,28 @@ fi
 
 #========================================================================================================================#
 
+aur_dep_order(){
+
+
+if 	[[ -e /usr/lib/aurutils/aur-depends ]] ; then
+	/usr/lib/aurutils/aur-depends -n "${package}" \
+	| grep -v "${package}" \
+	| pacman -r "${chroot}" -T - 2>/dev/null
+fi
+
+if	[[ -e /usr/bin/auracle ]] ; then
+	auracle buildorder "${package}" \
+	| awk '/AUR/ {print$2}' \
+	| uniq \
+	| xargs -n1 \
+	| grep -v "${package}" \
+	| pacman -r "${chroot}" -T - 2>/dev/null
+fi
+
+}
+
+#========================================================================================================================#
+
 aur_mkdepends_list(){
 
 	echo; echo "${czm} Checking for AUR build dependencies."
@@ -257,16 +309,6 @@ if	[[ -n ${aurdeps[*]} ]]; then
 	echo; echo "${czm}  NO AUR dependencies needed:"; echo
 fi
 
-}
-
-#========================================================================================================================#
-
-chroot_pacman(){
-
-	Database="${chroot}/var/lib/pacman/"
-	Pacconf="${chroot}/etc/pacman.conf"
-
-	sudo pacman -r "${chroot}" -b "${Database}" --config "${Pacconf}" --noconfirm "${@}" || { export ChrootPacmanExitCode="${?}" ; }
 }
 
 #========================================================================================================================#
@@ -382,28 +424,14 @@ fi
 
 #========================================================================================================================#
 
-fetch_source(){
+chroot_pacman(){
 
-	cd "${homebuilduser}" || { echo "Is chroot not setup? Run: aurch --setup before -B." ; exit ; }
+	Database="${chroot}/var/lib/pacman/"
+	Pacconf="${chroot}/etc/pacman.conf"
 
-if	[[ -d  "${package}" ]] && [[ -d "${package}"/.git ]]; then
-
-	cd "${package}"										|| { echo "[line ${LINENO}]" ; exit ; }
-	git pull
-	git cat-file -p "$(git rev-parse HEAD)":./PKGBUILD >PKGBUILD
-
-	sudo systemd-nspawn -q -D "${chroot}" -u builduser --chdir="${chrbuilduser}/${package}" --pipe \
-	makepkg --printsrcinfo >.SRCINFO						# SC2024: Is not ran as sudo within chroot.
-	cd "${homebuilduser}"									|| { echo "[line ${LINENO}]" ; exit ; }
-else
-	if	! git clone https://aur.archlinux.org/"${package}".git ; then
-		echo; echo "${czm}  Git clone failed. Switching to snapshot download."; echo
-		curl -L -O https://aur.archlinux.org/cgit/aur.git/snapshot/"${package,,}".tar.gz
-		tar xvzf   "${package}.tar.gz"
-	fi
-fi
-
+	sudo pacman -r "${chroot}" -b "${Database}" --config "${Pacconf}" --noconfirm "${@}" || { export ChrootPacmanExitCode="${?}" ; }
 }
+
 #========================================================================================================================#
 												
 manual_pgp_key(){
@@ -415,40 +443,22 @@ exit
 
 #========================================================================================================================#
 
-aur_dep_order(){
 
-
-if 	[[ -e /usr/lib/aurutils/aur-depends ]] ; then
-	/usr/lib/aurutils/aur-depends -n "${package}" \
-	| grep -v "${package}" \
-	| pacman -r "${chroot}" -T - 2>/dev/null
-fi
-
-if	[[ -e /usr/bin/auracle ]] ; then
-	auracle buildorder "${package}" \
-	| awk '/AUR/ {print$2}' \
-	| uniq \
-	| xargs -n1 \
-	| grep -v "${package}" \
-	| pacman -r "${chroot}" -T - 2>/dev/null
-fi
-
-}
-
-#========================================================================================================================#
 						### Testing ###
 test_run(){
 
 # list=(aura-bin auracle-git aurutils bauerbill pacaur pakku-git paru pbget \
 	# pikaur pkgbuilder repoctl rua trizen yaah yay aws-cli-git python-pyalsaaudio)
 
-#list=(aws-cli-git clion python-pyalsaaudio)
+# list=(aws-cli-git clion python-pyalsaaudio)
 
-#for package in "${list[@]}"
+# for package in "${list[@]}"					# SC2154: list is commened
 #	do
-#		echo; echo "${czm} BUILDING: ${buildpkg} "; echo
-#		./aurch-dev5 -B "${buildpkg}"
+#		echo; echo "${czm} BUILDING: ${buildpkg}"; echo
+#		./aurch-dev8 -B ${buildpkg}
 #	done
+#
+# return
 
 	depends=$(curl --compressed -s "https://aur.archlinux.org/rpc/?v=5\&type=info&arg\[\]=${buildpkg}" \
 	| jshon -e results -a -e  Depends 2>/dev/null \
@@ -490,12 +500,13 @@ fi
 while :; do
 	case "${1}" in
 	-B|--build)		build_pkg "${3}"							;;
-	   --setup)		set_up									;;
-	   --testrun)		test_run								;;
-	   --pgp)		key="${2}" manual_pgp_key						;;
+	--setup)		set_up									;;
+	--chrootpacman)	shift; chroot_pacman "${@}"	  						;;
+	--testrun)		test_run								;;
+	--pgp)			key="${2}" manual_pgp_key						;;
 	-h|--help)		help									;;
-	 -?*)                    echo; echo "${czm}${error} Operation error. Running help" ; help	;;
-	  *)			break
+	-?*)                    echo; echo "${czm}${error} Operation error. Running help" ; help	;;
+	*)			break
         esac
     shift
 done
